export const GET_CLIENT_DETAILS = "GET_CLIENT_DETAILS";
export const SET_CLIENT_DETAILS = "SET_CLIENT_DETAILS";
export const GET_ITEM_DETAILS = "GET_ITEM_DETAILS";
export const SET_ITEM_DETAILS = "SET_ITEM_DETAILS";
export const GET_DRIVER_DETAILS = "GET_DRIVER_DETAILS";
export const SET_DRIVER_DETAILS = "SET_DRIVER_DETAILS";
export const GET_ERRORS = "GET_ERRORS";